### PR TITLE
add postcss-filter-stream to plugins list

### PR DESCRIPTION
**Pull request by tsm91**
Hi @himynameisdave, i would like to add [postcss-filter-stream](https://github.com/tsm91/postcss-filter-stream) to the plugins list.

### CODE REVIEW

**Comment by tsm91** [comment]
ping @ai, if you find everything alright can you merge this one?

**Comment by ai** [comment]
@tsm91 it is not my repo :)

**Comment by tsm91** [comment]
@ai ah okay :D

**Comment by himynameisdave** [comment]
@ai you do have full access though :smile:

**Comment by tsm91** [comment]
@himynameisdave thanks :)

**Pull request merged**
